spring.application.name=integration-test-sample

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL defaults (overridden by local profile)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update